<Set_profile_section>:
    name: "set_profile_section"
    BoxLayout:
        size: root.width, root.height
        orientation: 'vertical'
        Section_header:
            header_text: "Set profile"
        ScrollView:
            MDList:
                OneLineListItem:
                    id: item2
                    text: "Profile1"
                OneLineListItem:
                    id: item2
                    text: "Profile2"

        Nav_bar: